### ISSUE TITLE
Performance of Find()

### ISSUE THREAD

**Issue by benfiveblocks** [alexedwards/scs#111]
I implemented a custom session store based on memstore, that also save to disk on Commit() and Delete(). This provides good performance for Find(), and also preserves sessions between server updates. This works well for me because I have a single web server. How can I keep the good performance for Find(), and also support cross-server sessions? E.g. Gorilla can store sessions in cookies.

**Comment by alexedwards** [comment]
Hi,

The scope of this package is limited to stateful sessions, so storing session data in a cookie is out of scope and you'll need to use something like Gorilla sessions.

If you're running multiple web servers, then you have two main options:

1. Set up your load balancer to use 'sticky sessions' so that requests with the same session are always routed to the same server.
2. Use an alternative session store with a backend that is available to all your webservers. Using Redis and the Redisstore SCS implementation is probably the fastest.
