### ISSUE TITLE
panic in getSessionDataFromContext makes this package hard to work with

### ISSUE THREAD

**Issue by deltamualpha** [alexedwards/scs#114]
Hello,

I was a happy user of the v1 of this package, and recently decided to upgrade to v2, however, I found some of the new behaviors extremely difficult to work with.

One piece in particular was the fact that the package throws a `panic` if you try and load a session from a request that doesn't have a session attached: [getSessionDataFromContext](https://github.com/alexedwards/scs/blob/f336450b94218d525622c490bfab66f610d1255f/data.go#L504). Previously, I could attempt to load a session blindly, and based on the response from the function, I'd know if the request had a session attached. Now, I have to make absolutely sure that I've got the `LoadAndSave` middleware inserted all over the place.

Panics thrown from userland are pretty unidiomatic in go, I feel, and the only way to really handle them is by doing the defer-recover dance, which is messy and error-prone. I'm likely going to migrate to another session-management library.

**Comment by alexedwards** [comment]
Hi : )

The decision to panic in `getSessionDataFromContext()`, rather than return an error, in v2 was something I thought about carefully and wasn't a choice I made lightly.

The way I view it,  you should only be calling `sessionManager.XXXX(ctx)`  when you logically expect the `ctx` you are passing in to actually contain a session. It's a bit like calling a function like `io.WriteString()` without actually passing a valid `io.Writer` as the first parameter --- if you call `io.WriteString(nil, "foo")` you'll get a runtime panic.

Panics for *expected* errors (e.g. database query timeout, a network resource being unavailable, or bad user input) that may happen at runtime are unidiomatic in Go. In contrast, panics for *unexpected* errors (e.g. a logical error ---  like trying to access an out-of-bounds index in a slice, or trying to close an already-closed channel --- or trying to use language or package features in an unintended way) are much more acceptable. There's a lot of precedent for this in the std lib packages.

Calling `sessionManager.XXXX(ctx)` when no sesson data exists in the provided context firmly feels to me like a unexpected logic error in a codebase, and I don't think that panicing in that scenario is unidiomatic.

Personally, I usually wrap all my main application routes (i.e. all those that aren't serving static files, or performing some other special function) with the `LoadAndSave()` middleware and it works fine. Using something like alice (https://github.com/justinas/alice) or a router which supports middleware 'groups'  like chi can be helpful here and saves you from having to remember to wrap individual handlers.

**Comment by theckman** [comment]
@alexedwards how can I inspect a context to know whether or not it has the appropriate session inside, to selectively avoid invoking your code (thus seeing the panic)?

**Comment by alexedwards** [comment]
@theckman Can you explain the scenario in which would you need to do that? Why would you want to perform an session operation on a context which may or may not contain a session?

**Comment by deltamualpha** [comment]
To put some more color on my use-case: I'm writing an authentication microservice that needs to collate nearly a half-dozen different ways that a request could be authenticated. I have handlers and middleware in that service that want to treat the presence or absence of a "valid" session -- not just an empty, uninitialized one -- as a signal, and fall through various authentication methods without having to do a weird `recover()` dance. (In other words, if a user provided a session cookie _is_ a meaningful distinction for me, not just "is there a value in the session or not".)

I'm not sure I buy the difference between "expected" and "unexpected" errors. Panics should be, in my opinion, reserved for cases where there's truly no reasonable way for execution to continue. Everything else is just an error that can be returned as a value and handled as part of the normal execution flow. Throwing a panic because _an expected value is not present in a context_, which is what this case boils down to, feels especially unpleasant.

**Comment by alexedwards** [comment]
One option could be to add a new `SessionManager.ValidContext(ctx)` method which returns `true` if the provided context contains a valid `session`. You could then use this to check for the presence of a valid session before calling any other methods (thereby avoiding the panic in your workflow). The documentation for this method could include the necessary warnings and explain the risks of using it in your code.

**Comment by alexedwards** [comment]
If there's any desire to see `SessionManager.ValidContext(ctx)` added, please comment and I'll reopen this issue.

**Comment by fouadyahyaoui** [comment]
@alexedwards What about allowing the user to configure if `getSessionDataFromContext()` should panic or not?
For instance adding a mustGetSessionDataFromContext() function as default, which panics, and a `getSessionDataFromContext()` function which does not panic, but does return a `ErrNoSession` error.
