### ISSUE TITLE
mysqlstore with MySQL < 5.6: UTC_TIMESTAMP(6) parameter unsupported

### ISSUE THREAD

**Issue by casipw** [alexedwards/scs#17]
With MySQL before version 5.6, I get SQL errors in mysqlstore.go. They are caused by `UTC_TIMESTAMP(6)`. The parameter was introduced in MySQL 5.6.4 ([see the docs](https://dev.mysql.com/doc/refman/5.6/en/date-and-time-functions.html#function_utc-timestamp)) and "is given to specify a fractional seconds precision from 0 to 6". In MySQL 5.6, they also changed the default format from `'YYYY-MM-DD HH:MM:SS' or YYYYMMDDHHMMSS.uuuuuu` to `'YYYY-MM-DD HH:MM:SS' or YYYYMMDDHHMMSS`.

I'm not sure if it a "MySQL version switch" in mysqlstore would be feasible. But is it necessary to store the expiry timestamp with such a precision at all? Would't one second be precise enough? Then we could omit the parameter of `UTC_TIMESTAMP(6)`.

**Comment by bradleyfalzon** [comment]
> Would't one second be precise enough? Then we could omit the parameter of UTC_TIMESTAMP(6).

I tend to agree, this only used as part of the cleanup routine, the < 1 second precision there could be dropped.

**Comment by alexedwards** [comment]
I use sub-second session lifetimes and idle-timeouts (~100 milliseconds) in my unit tests - it means they run nice and fast. I do think supporting them is useful for testing purposes, if nothing else.

The other benefit of using nanosecond (or microsecond, depending on the storage engine) precision for expiry times is that the behavior of SCS is more exact, consistent and predictable across the range of `time.Duration`s that Go supports. If expiry times are rounded to the nearest second, then sessions may expire/not expire predictably due to the rounding when the session lifetime is around the 1 second mark.

My preference is for sub-second expiry precision should remain the norm unless the storage engine simply doesn't support it (like the older MySQL version).

Which... doesn't solve your problem!

Yes, a switch which changes the `Find` and `deleteExpired` functions to use `UTC_TIMESTAMP` instead of `UTC_TIMESTAMP(6)` could probably be added, based on the output from `SELECT VERSION()`.

@casipw Could you confirm what the output of your `SELECT VERSION()` is?

**Comment by alexedwards** [comment]
@bradleyfalzon It's also used in `Find`. Engine's should return false if the current time is > the expiry time. It's important because sessions may have expired, but still exist in the table because we happen to be in-between cleanup routines.

**Comment by casipw** [comment]
@alexedwards `SELECT VERSION()` returns `5.1.73-log` on my server (CentOS 6.9).

**Comment by alexedwards** [comment]
@casipw I've pushed a fix for this in commit https://github.com/alexedwards/scs/commit/0fdd3ef0cedf798548a2a904932bc0b4e13ee91b. 

I don't have an old version of MySQL to test it on though. Can you confirm that it works as expected?

The only change you should need to make is to use the following table definition instead:

```sql
CREATE TABLE sessions (
  token CHAR(43) PRIMARY KEY,
  data BLOB NOT NULL,
  expiry TIMESTAMP NOT NULL
);
CREATE INDEX sessions_expiry_idx ON sessions (expiry);
```

**Comment by casipw** [comment]
@alexedwards It works! Thank you very much!
