### ISSUE TITLE
Sign session ids/tokens

### ISSUE THREAD

**Issue by bramvbilsen** [alexedwards/scs#195]
Is there a possibility to sign the session ids that are sent to the client to check for tampering?

**Comment by alexedwards** [comment]
The session IDs contain 256-bits of entropy and are generated with a CSRNG. Any tampering to the ID will just result in a failed lookup in the storage backend, the same there would be with an expired session.

As far as I know, signing the session IDs is not necessary or a part of the standard pattern for implementing server-side session storage (client-side storage, yes absolutely --- but not server-side storage where then only thing send to the client is a large-and-random-enough session ID).

**Comment by bramvbilsen** [comment]
It might be interesting for the following case though:
A database breach happens and an attacker gets access to all session data. They can now pretend to be any logged in user as they have access to the session token.
When the keys are signed, the attacker can’t use this. As they do not know how to sign the tokens.

I think this might be a nice extra layer of protection. Would you be open for a PR if implemented? Or do you believe it’s out of scope?

**Comment by alexedwards** [comment]
In that scenario, signing the stored tokens using a HMAC isn't necessary. Storing a fast hash (SHA-256) of the token would suffice, as the attacker can't determine the token from the SHA-256 hash, and the tokens are 256-bit random values so a 'rainbow table' approach won't work.

I'm not against the idea storing a SHA-256 hash of the token in the stores, rather than a plaintext value, but that's an altogether different issue to signing the session ID that is sent to the client.

**Comment by bramvbilsen** [comment]
Would you be open to a PR implementing this as an opt-in feature?

**Comment by alexedwards** [comment]
Yes, if you have the time and interest a PR would be great :+1: 

I would suggest adding a boolean `HashTokenInStore` option to `SessionManager` (default value of false). If set to true, I think the  `doStoreDelete`, `doStoreFind` and `doStoreCommit` functions should create a hash of the regular token with SHA256 and then encoded using `base64.RawURLEncoding.EncodeToString()` (so that the regular and hashed tokens have exactly the same format --- which should maximise compatibility with the existing store implementations), and pass the hashed token when calling the store.

The token sent to the client should not be hashed at all. The code changes touch some of the most important parts of the codebase, so we'll also need to include tests for the new functionality.
