### ISSUE TITLE
Do I have to check for nil values in Get()?

### ISSUE THREAD

**Issue by CaledoniaProject** [alexedwards/scs#224]
The example code in the godoc is quite confusing to me,

//	foo, ok := session.Get(r, "foo").(string)
//	if !ok {
//		return errors.New("type assertion to string failed")
//	}

Am I supposed to invoke Get and do type conversion on possible nil values? Or does the library ensure Get() always return non-nil values?

**Comment by cerpmath123** [comment]
Yes, you do. However, `Get()` returns an interface and since you most likely need to type-assert this value anyway, doing it like 
```
foo, ok := val.(string)
if !ok {
// handle the error
}
```
sets `ok` to `false`  whenever `val` is `nil` (or any other error occurs).

See [this playground](https://go.dev/play/p/jy3lQQf6ISN) for an example.

It is recommendable to use the `GetString()`, `GetInt()` or `GetBytes()` methods. `GetString()` returns an empty string if the value does not exist (or is of a non-assertable type).

**Comment by CaledoniaProject** [comment]
Yes, GetString() works fine
