### ISSUE TITLE
Add manager.Opts() method to expose option

### ISSUE THREAD

**Issue by rskumar** [alexedwards/scs#30]
Since Opts is not exposed, custom middleware extension is not possible, in case I want to write my own middleware.
Referring https://github.com/alexedwards/scs/blob/876a0fdbdd8ce6c328b2e8064a7483ff377ddaa4/manager.go#L114 , m.opts.Timeout cannot be accessed from outside package.

What if by adding manager.Opts() method, which returns opts.

**Comment by alexedwards** [comment]
Hi,

Could you quickly explain the reason behind needing to make a custom middleware extension? Is it because the error handling doesn't suit, or something else?

Thanks

**Comment by rskumar** [comment]
To use in Echo framework, I can write custom middleware and pass sessionManager in their echo.Context.

**Comment by jpfluger** [comment]
I think I see what @rskumar is asking about. He can correct me if I'm wrong. 

Two points:

First regarding echo middleware - @rskumar - maybe you can use my scs echo middleware [example](https://github.com/alexedwards/scs/issues/31#issuecomment-360700529). Note the function `NewSessionManagerRedis`.

Secondly, the following demonstrates the current way to configure manager options individually

```golang
sessionManager := scs.NewManager(engine)
sessionManager.Name("sessionid")
sessionManager.Path("/")
sessionManager.Lifetime(60 * time.Minute)
sessionManager.Secure(false)
sessionManager.HttpOnly(true)
sessionManager.IdleTimeout(20 * time.Minute)
sessionManager.Persist(true)
```

but @rskumar would prefer to

```golang
sessionManager := manager.NewManager(engine)
sessionManager.Opts(&manager.Opts{
     Name: "sessionid",
     Path: "sessionid",
     Lifetime: 60 * time.Minute,
})
```

or use the abbreviated

```golang
sessionManager := manager.NewManagerWithOpts(engine, &manager.Opts{
     Name: "sessionid",
     Path: "sessionid",
     Lifetime: 60 * time.Minute,
})
```
or even better create a `ManagerConfig` struct. This would allow you to keep both `Manager.store` and `Manager.opts` private. 

```golang
sessionManager := manager.NewManagerWithConfig(&ManagerConfig{
     Engine: &engine, 
     Opts: &manager.Opts{
          Name: "sessionid",
          Path: "sessionid",
          Lifetime: 60 * time.Minute,
     }
})
```

The use case to make Opts configurable is that some websites initiate via config file (eg json). In this case, the `opts` section gets marshaled into initializing the manager directly rather than having to build a mapping abstraction.

Although you could make [manager.opts](https://github.com/alexedwards/scs/blob/876a0fdbdd8ce6c328b2e8064a7483ff377ddaa4/manager.go#L15) public and not break code(?), it's just as safe to keep `manager.opts` and `manager.store` private -- then create

* `manager.Opts()`
* `type ManagerConfig struct` with Opts and Engine as params
* `manager.NewManagerWithConfig()`

Is this what @rskumar is going for?  Anyone else's thoughts?

**Comment by alexedwards** [comment]
Thanks both. I agree, exposing `Opts()` seems like it will help open up solutions to a few of the current issues.

**Comment by alexedwards** [comment]
I've pushed commit https://github.com/alexedwards/scs/commit/6f643f463fb7b69725742682bd5f2a10237e2c9a which moves the `opts.idleTimeout > 0 ` check into the `Touch` method itself and I think fixes this issue. 

The `Manager.Use` middleware now doesn't rely on anything unexported (types or fields) so you should be able to easily create your own middleware. The standard one looks like this:

```go
func (m *Manager) Use(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		session := m.Load(r)

		err := session.Touch(w)
		if err != nil {
			log.Println(err)
			http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
			return
		}

		ctx := m.AddToContext(r.Context(), session)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
```

It's a different solution to the problem than exposing `Opts()` but after thinking about it for a while it seems like a simpler way to address the problem.

**Comment by rskumar** [comment]
Thank you.
