### ISSUE TITLE
Wasting cookie bytes in cookie store....

### ISSUE THREAD

**Issue by mvrhov** [alexedwards/scs#46]
Why are we wasting 11bytes (15 later when base 64 encoded) of cookie data with converting UnixNano to string representation.

**Comment by mvrhov** [comment]
Having SessionStore as interface would help here.

**Comment by alexedwards** [comment]
It's because the UnixNano representing the expiry time needs to be be transformed --- one way or another --- into a `[]byte` so it can be subsequently passed as part of the message to the `secretbox.Seal()` function.

An alternative might be to use `binary.Write()` like this: https://stackoverflow.com/a/26114897. I haven't tested it out completely, but I think that would only use 8 bytes.

Happy to accept a PR for this, if you'd like to submit one?

**Comment by alexedwards** [comment]
Support for client-side sessions with cookiestore was removed in v2 -- it now supports server-side stores only.
